package com.dthxhieu.ticket_booking_system_be.booking.dto.request;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

// Request body for POST /api/v1/bookings (US-13).
//
// The client sends the EventSession ID and the list of SeatHold IDs
// created by US-12. One SeatHold ID corresponds to exactly one seat.
//
// Fields NOT accepted from the client (calculated server-side):
//   - userId      (from Spring Security context)
//   - price       (eventSession.basePrice × seat.priceMultiplier)
//   - totalAmount (SUM of item prices)
//   - bookingCode (generated by service)
//
// Duplicate seatHoldIds validation is done in the Service layer
// because Jakarta Validation cannot detect list-level duplicates.
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateBookingRequest {

    @NotNull(message = "Event session ID is required.")
    private Long eventSessionId;

    // Each ID corresponds to one SeatHold record (one seat).
    // Must not be empty — a booking requires at least one seat.
    @NotNull(message = "Seat hold IDs are required.")
    @NotEmpty(message = "At least one seat hold ID is required.")
    private List<Long> seatHoldIds;
}
