CREATE TABLE password_reset (
    id          BIGSERIAL PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    otp_code    VARCHAR(6)   NOT NULL,
    expired_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    attempt_count SMALLINT   NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
